### ISSUE TITLE
Testkit APP_HOME Compatibility

### ISSUE THREAD

**Issue by 0x199** [OpenOrbis/OpenOrbis-PS4-Toolchain#115]
Considering the number of people with a testkit is very low, this issue's priority is probably low aswell. Still wanted to make an issue about it so it can be addressed someday in the future _if testkit is meant to be supported aswell_. 

The earlier toolchains used to be compatible with APP_HOME, which was really nice for quickly designing a UI, for example. In the newer toolchain releases APP_HOME instantly crashes while loading `eboot.bin`. I'm not exactly sure in which release it broke.

Crashlog:

```
<118>D/99301:Sysmodule:
<118>libSceFios2.sprx is loaded from the development machine system.
<118>D/99301:Sysmodule:
<118>libc.sprx is loaded from the development machine system.
#
# A user thread receives a fatal signal
#
# exception: 0xa002030a (SYSTEM_ILLEGAL_FUNCTION_CALL)
# thread ID: 100899
# thread name: eboot.bin
# proc ID: 90
# proc name: eboot.bin
#
# registers:
# rax: 0000000000000000  rbx: 0000000000000000
# rcx: 00000007ef662b8e  rdx: 0000000000000000
# rsi: 00000007ef662a60  rdi: 0000000000000001
# rbp: 0000000000000000  rsp: 00000007ef662a50
# r8 : 0000000000002000  r9 : 000000000000003e
# r10: 000000000515ca11  r11: 0000000000000246
# r12: 00000007ef662a60  r13: 000000000000003e
# r14: 0000000000000000  r15: 00000000523d8278
# rip: 0000000052392b05  eflags: 00000202
# BrF: 000000005239dfa2  BrT: 0000000052392abb
#
# backtrace:
#
# dynamic libraries:
# /hostapp/app/eboot.bin
#  text: 0000000052340000:00000000523cc000 r-x
#  data: 00000000523d8000:00000000523dc000 rw-
#  fingerprint: 4f50454e4f524249532d484f4d45425245570000
# /PFplYQqaXf/common/lib/libkernel.sprx
#  text: 0000000801280000:00000008012cc000 r-x
#  data: 00000008012d0000:0000000801308000 rw-
#  fingerprint: 353c1fb6d50b83b632830643318d7c3d00000000
# /PFplYQqaXf/common/lib/libSceLibcInternal.sprx
#  text: 0000000819db8000:0000000819ebc000 r-x
#  data: 0000000819ec4000:0000000819ee4000 rw-
#  fingerprint: 6cfb1a5e5ffc646e94f333e5169b663300000000
[...]
```

I'm available for testing if needed.

**Comment by Cryptogenic** [comment]
What firmware is this on? Is this on a recently exploited firmware such as 7.50/7.55?

**Comment by 0x199** [comment]
The crashlog is from 5.05, I've not tested higher firmware.

**Comment by Cryptogenic** [comment]
Would it be possible to send the eboot.bin for root causing? if not, can you the instructions + offsets for the function where the exception occurs @ `0x52392b05 - 0x52340000 = 0x52B05`?

**Comment by 0x199** [comment]
As requested: [eboot.zip](https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/files/6214042/eboot.zip)

**Comment by Cryptogenic** [comment]
Yeah so the crash is in `__stdio_write` in MUSL.

```
0000068b  4c89e6             mov     rsi, r12 {var_58}
0000068e  0f05               syscall 
00000690  -- crash --
```

The problem is the invoke of the syscall instruction. Sony has a custom mitigation where syscall instructions can only be executed from libkernel, so if a homebrew app tries to use a syscall instruction it's sent a crash signal. This is a result of our move from linking with the system libc to linking with MUSL for things like libcxx.

What you can do is use the libc headers and build files from older toolchain releases before we integrated with MUSL and merge them with the latest toolchain, but it's a hacky solution. Other than that, I don't see an easy way to tackle this issue, especially since it's a non-issue if you're jailbroken and only affects unjailbroken testkits, so I'll close as informational for now.
