### ISSUE TITLE
Move tools into dedicated repos

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#164]
We should clean up the main repository and remove redundant code. We'll do this by moving tools into their own repos and using this one for headers, samples, final build stuff, and tests.

The following will be moved into separate repos and removed from the main repository:
- [x] create-fself (previously create-eboot/create-lib)
- [x] create-gp4
- [x] orbisLibGen
- [x] readelf

The following will be removed entirely, and will be moved to part of the build process or are to be revisited at a later date:
- [x] lib stub autogenerated sources
- [x] miralib (C#)

**Comment by SK83RJOSH** [comment]
I know this issue was closed, but I'd also like to suggest doing the same for ports of third party libraries. Not a big fan of SDL and STB being included in the toolchain itself. Would much prefer these be hoisted out so they can be maintained by those interested; and/or so people can easily drop in their own versions. I can definitely see everything being in the system include path causing issues in the long run.  Wouldn't take much effort to do, and would declutter things significantly. 👍

**Comment by Cryptogenic** [comment]
> I know this issue was closed, but I'd also like to suggest doing the same for ports of third party libraries. Not a big fan of SDL and STB being included in the toolchain itself. Would much prefer these be hoisted out so they can be maintained by those interested; and/or so people can easily drop in their own versions. I can definitely see everything being in the system include path causing issues in the long run. Wouldn't take much effort to do, and would declutter things significantly. 👍

@SK83RJOSH In theory I agree, it's bloating the repository. The problem (mainly with SDL) is it's really crappy to build. Will look into moving this into getting this on a CI and removing from this repo though.
