### ISSUE TITLE
AF_INET6 is 28 on PS4

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#58]
`AF_INET6` is 28 on both stock FreeBSD and PS4, but is erroneously set to 10 in the OpenOrbis headers. There may be other similar errors.

**Comment by Cryptogenic** [comment]
So this is due to discrepancies between MUSL and BSD headers where MUSL is a linux-based libc. There are many other discrepancies in various headers that need to be adjusted. I may make this into a new bigger issue. Sorry for the late response, been away and not had great internet access :P 

Will address in a commit soon.
