### ISSUE TITLE
CMath C++ header broken

### ISSUE THREAD

**Issue by kiwidoggie** [OpenOrbis/OpenOrbis-PS4-Toolchain#64]
```
using ::signbit;
using ::fpclassify;
using ::isfinite;
using ::isinf;
using ::isnan;
using ::isnormal;
using ::isgreater;
using ::isgreaterequal;
using ::isless;
using ::islessequal;
using ::islessgreater;
using ::isunordered;
using ::isunordered;
```

These functions are not implemented and making flatbuffers fail.

**Comment by Cryptogenic** [comment]
Related LLVM issue: https://reviews.llvm.org/D18501.

Essentially the FreeBSD target uses macros instead of functions for various cmath helpers like `signbit()` and `fpclassify()`, which results in the `using` statements becoming compiler errors. By removing those statements for FreeBSD targets these errors are resolved. This however does result in an additional `no template named 'numeric_limits'` error, however this can be resolved by using `#include <limits>`.

Will ship a fix for this in the morning.
