### ISSUE TITLE
mbstowcs() wcstombs() functions crash

### ISSUE THREAD

**Issue by 0x199** [OpenOrbis/OpenOrbis-PS4-Toolchain#84]
As discussed with kiwi [on Discord](https://discord.com/channels/464237083335327744/467502160213704725/744292105970647060), function `mbstowcs` and `wcstombs` seem to always crash (maybe more but these two were tested).

I haven't been able to figure out the cause of the crash. Kiwi mentioned the entry in the table is null.

Crash log:
```
<118>[UIProcess] malloc stats freeSize:41791008 (100%) inuseSize:152032 peakSize:152480 [pid:0x38]
#
# A user thread receives a fatal signal
#
# signal: 11 (SIGSEGV)
# thread ID: 101599
# thread name: eboot.bin
# proc ID: 106
# proc name: eboot.bin
# reason: page fault (user read data, page not present)
# fault address: 0000000000000000
#
# registers:
<118>[VCS]checkApplicationStatus() [LNC->VCS] App was Suspended. appId = 0x60001f0b.
# rax: 0000000000000000  rbx: 00000007efeded24
# rcx: 0000000000000000  rdx: 000000000000000f
# rsi: 00000007efedeac0  rdi: 00000007efedeb90
# rbp: 0000000000000000  rsp: 00000007efedeaa0
# r8 : 0000000000000000  r9 : fefefefefefefeff
# r10: 0000000000000018  r11: 0000000000000003
# r12: 00000007efededc8  r13: 0000000000000000
# r14: 00000007efedeac0  r15: 00000007efedeb90
# rip: 00000000067a19b5  eflags: 00010246
# BrF: 00000000067a1988  BrT: 00000000067a19a5
```

Tested with the following code:

```
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

int main()
{
	char title[] = "Some test string";

	wchar_t inputTextBuffer[100];
	mbstowcs(inputTextBuffer, title, sizeof(title));

	printf("Out: %ls\n", inputTextBuffer);

	return 0;
}
```

**Comment by sleirsgoevy** [comment]
`mbsrtowcs()` queries `__pthread_self()->locale->cat[LC_CTYPE]` to determine whether the input should be treated as Unicode. `__pthread_self()` is implemented as `asm volatile("mov fs:0, %0":"="(self));`, and what it points to seems to be managed by the PS4 dynamic linker, not by us. As a consequence, the memory that is treated as `__pthread_self()->locale` does not contain a valid pointer.

As in our case the libc is not managing the TLS, `__pthread_self()` should be implemented as a TLS variable instead of this assembly magic.
